#!/usr/bin/zsh 

set -e

HEADER="Accept: application/vnd.github.v3+json;"
URL="https://api.github.com/repos/apache/kafka/pulls"
PARAMS="?state=closed&perpage=100"

USERNAME=$1
TOKEN=$2

MAX=`curl -u $USERNAME:$TOKEN -siH "$URL" $URL$PARAMS | grep -oP "(?<=rel=\"next\")(.*)(?=rel=\"last\")" | grep -oP "(?<=&page=)(\w+)" `

TMP=$(mktemp -d)
MAX=3
echo "Extracting pull requests."
for i in $(seq 0 $MAX); do
	# Prints progress of the loop
	n=$(awk -v var_i=$i -v var_MAX=$MAX 'BEGIN { printf("%3.0f", var_i/var_MAX*100)}')
	printf "%${n}s\r" | tr " " "#"
	
	# Extracts the page to a json temporary file 
	curl -u $USERNAME:$TOKEN -sH "$HEADER" "$URL$PARAMS&page=$i" > "$TMP/page_$i.json"
	
	# If goes close the github api limit, rest for 1 minute
	[[ $i -ne 0 ]] && [[ $(($i % 30)) -eq 0 ]] && sleep 1m
		
done;

OUT=./files.tar.gz
[[ -f $OUT ]] && rm $OUT
tar -zcf $OUT -C $TMP .

echo "\nExtracted the pull requests to: \e[4m$OUT\e[0m"
exit 0
